name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.0

            - name: Install
              run: npm install --legacy-peer-deps

            - name: Build blog content
              run: npm run build:content

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm test
